server:
  port: 8080

spring:
  application:
    name: securitymak

  datasource:
    url: jdbc:postgresql://localhost:5432/securitymak_db
    username: securitymak_user
    password: securitymak123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        "format_sql": true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    

logging:
  level:
    "org.springframework.security": DEBUG
    "org.hibernate.SQL": DEBUG

jwt:
  secret: securecase-super-secret-key-256-bits-long!!!
  expiration: 86400000


